name: Terraform Infra Pipeline

on:
  workflow_dispatch:

jobs:
  tf-infra:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.0

    - name: aws configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }} #need a vars.region
    
    - name: Terraform Init
      run: terraform init
      working-directory: tf4

    - name: Terraform Validate
      run: terraform validate
      working-directory: tf4
    
    - name: Terraform Plan
      run: terraform plan
      working-directory: tf4
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: tf4

# run commands with out writing out each cmd
    # - name: tf workflow
    #   run: |
    #     cd tf4
    #     terrafomr init
    #     terraform validate
    #     terraform plan
    #     terraform apply